# Generated by Django 4.2.7 on 2023-11-10 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time')),
                ('qty', models.FloatField(verbose_name='Quantity')),
            ],
            options={
                'verbose_name_plural': 'Calories Consumptions',
            },
        ),
        migrations.CreateModel(
            name='CalorieGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.PositiveIntegerField(verbose_name='Goal')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Exercise Name')),
                ('description', models.TextField(verbose_name='Exercise Description')),
                ('gif', models.URLField(verbose_name='GIF URL')),
            ],
            options={
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Exercise Type',
                'verbose_name_plural': 'Exercise Types',
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Muscle Group',
                'verbose_name_plural': 'Muscle Groups',
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Routine Name')),
                ('description', models.TextField(verbose_name='Routine Description')),
            ],
            options={
                'verbose_name_plural': 'Routines',
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_time', models.PositiveIntegerField(verbose_name='Rest Time')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('reps_goal', models.PositiveIntegerField(verbose_name='Reps Goal')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.exercise', verbose_name='Exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.routine', verbose_name='Routine')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Unit of Measurement',
                'verbose_name_plural': 'Units of Measurement',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField(verbose_name='Schedule')),
                ('name', models.CharField(max_length=255, verbose_name='Workout Name')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration')),
                ('is_freestyle', models.BooleanField(default=False, verbose_name='Is Freestyle')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking_app.routine', verbose_name='Routine')),
            ],
            options={
                'verbose_name_plural': 'Workouts',
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_time', models.PositiveIntegerField(verbose_name='Rest Time')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('reps_goal', models.PositiveIntegerField(verbose_name='Reps Goal')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.exercise', verbose_name='Exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.workout', verbose_name='Workout')),
            ],
            options={
                'verbose_name_plural': 'Workout Exercices',
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('principal_goal', models.CharField(max_length=50, verbose_name='Principal Goal')),
                ('reps_goal', models.PositiveIntegerField(verbose_name='Reps Goal')),
                ('actual_achievement', models.PositiveIntegerField(verbose_name='Actual Achievement')),
                ('actual_reps', models.PositiveIntegerField(verbose_name='Actual Reps')),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.workoutexercise', verbose_name='Workout Exercise')),
            ],
            options={
                'verbose_name_plural': 'Workout Sets',
            },
        ),
        migrations.CreateModel(
            name='RoutineSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('principal_goal', models.CharField(max_length=50, verbose_name='Principal Goal')),
                ('reps_goal', models.PositiveIntegerField(verbose_name='Reps Goal')),
                ('routine_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.routineexercise', verbose_name='Routine Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.PositiveIntegerField(verbose_name='Meal ID')),
                ('qty', models.FloatField(verbose_name='Quantity')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time')),
                ('meal_type', models.CharField(max_length=255, verbose_name='Meal Type')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.unitofmeasurement', verbose_name='Unit of Measurement')),
            ],
            options={
                'verbose_name_plural': 'Meals',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.exercisetype', verbose_name='Exercise Type'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_groups',
            field=models.ManyToManyField(to='tracking_app.musclegroup', verbose_name='Muscle Groups'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.unitofmeasurement', verbose_name='Unit of Measurement'),
        ),
    ]
